### ISSUE TITLE
Error building Oscam 11402 after changed TommyDS code in latest Oscam

### ISSUE THREAD

**Issue by nozorrog** [su-mak/osebuild#1]
Hi, Su-mak!
Trying to build latest Oscam 11402 binary I have an Error:

In file included from tommyDS_hashlin/tommychain.h:39:0,
from oscam-hashtable.c:1:
tommyDS_hashlin/tommytypes.h:66:2: error: #error Unsupported SIZE_MAX
#error Unsupported SIZE_MAX
^
make[2]: *** [build/arm-linux-androideabi-ssl/oscam-hashtable.o] Error 1
make[1]: *** [all] Error 2
make: *** [android-arm] Error 2

Never had this error building Oscam 11401 or earlier.
What's wrong? Thank You for your hard work!

**Comment by nozorrog** [comment]
Same error is still with Oscam 11410 building.

**Comment by su-mak** [comment]
change the script from android api 16 to minimum 21

ANDROID_API_LEVEL="21"

**Comment by nozorrog** [comment]
My STB is based on Android KK 4.4.2. So It's api level 19. Is this issue valid for api level 19? Thank You for your great job!

**Comment by nozorrog** [comment]
I tryed ANDROID_API_LEVEL= 21, 19 and even 22. No luck. Still same Build error.
I found a temporary solution for Oscam building. After latest Oscam source downloading I replace TommyDS code folder content with the old one from Oscam 11401 source and I build Oscam. It works.

**Comment by su-mak** [comment]
Android api 21-töl működnie kell.

Ha készítettél android toolchain-st és módosítottad az api-t, érdemes rendszer újraindítás mert  memóriába tárol és abból rakja össze az előzőt, android make-standalone-toolchain.sh hibája.

Töröld le (toolchains/arm-linux-androideabi) és próbáld rendszer újraindítással.

21 alatt:
add hozzá az utolsó előtti sorba: toolchains/arm-linux-androideabi/sysroot/usr/include/stdint.h

 /* Keep the kernel from trying to define these types... */
 #define __BIT_TYPES_DEFINED__
 
+#if defined(__LP64__)
+#  define SIZE_MAX       UINT64_MAX
+#else
+#  define SIZE_MAX       UINT32_MAX
+#endif
+
 #endif /* _STDINT_H */

Remélem, hogy segít.

**Comment by nozorrog** [comment]
Unfortunately, It doesn't work. Oscam build for API 21 doesn't work on Android 4.4.2 (API 19). We need another solution.

**Comment by nozorrog** [comment]
OK, It works well, but replacing TommyDS folder content is more simply. Doesn't exist another solution for this problem?

**Comment by su-mak** [comment]
### Sorry, my English knowledge is weak.

Android api 21 and later works well.

**older versions need to be repaired: 16 to 20 patch**
```
--- tmp/toolchains/arm-linux-androideabi-api-”xx”/sysroot/usr/include/stdint.h    2016-10-12 15:11:58.000000000 +0200
+++ tmp/toolchains/arm-linux-androideabi-api-”xx”/sysroot/usr/include/stdint.h    2018-04-09 20:55:16.272518638 +0200
@@ -259,4 +259,10 @@
 /* Keep the kernel from trying to define these types... */
 #define __BIT_TYPES_DEFINED__
 
+#if defined(__LP64__)
+#  define SIZE_MAX       UINT64_MAX
+#else
+#  define SIZE_MAX       UINT32_MAX
+#endif
+
 #endif /* _STDINT_H */
```

“If you modify api, you will need to restart the system, but only if you are rebuilding an Android toolbar.”

**Comment by su-mak** [comment]
```
I tryed ANDROID_API_LEVEL= 21, 19 and even 22. No luck. Still same Build error.
I found a temporary solution for Oscam building. After latest Oscam source downloading I replace TommyDS code folder content with the old one from Oscam 11401 source and I build Oscam. It works.
```

### What you've built api 21 is not api 21...
“If you modify api, you will need to restart the system, but only if you are rebuilding an Android toolbar.”

**Comment by nozorrog** [comment]
OK. Adding needed lines in stdint.h file helps well. We may close this thread. Thank You.
