### ISSUE TITLE
stapi "Openbox_Xcruiser"

### ISSUE THREAD

**Issue by satxtreme** [su-mak/osebuild#2]
Hi ! Pls fix PowerVu and others compile mistakes..many thanks

**Comment by su-mak** [comment]
You need to install XcamClient3, and replace the oscam bin file.

**Comment by su-mak** [comment]
PowerVu ever worked?

No error warning. [stapi.patch.zip](https://github.com/su-mak/osebuild/files/2760333/stapi.patch.zip)

**Comment by satxtreme** [comment]
Yes, it does not work only after compiling osebuild
p.s I'll post a log later

**Comment by satxtreme** [comment]
[build.log.zip](https://github.com/su-mak/osebuild/files/2760894/build.log.zip)
Only PowerVu  does not work

**Comment by su-mak** [comment]
I can not speak English well, I'm so sorry. 

If you replace the sent stapi.patch, errors will be resolved.
[build.log.zip](https://github.com/su-mak/osebuild/files/2761145/build.log.zip)

More info about the last working Powervu compilation, oscam svn, emu, etc... ?

**Comment by su-mak** [comment]
I don't know the exact settings, [they're trying here](http://www.altayebsat.com/vb/showthread.php?s=b69ac4658444d9a8cf1dc6eb37b64bfa&t=15657&page=29), I don't speak Arabic.

**Comment by satxtreme** [comment]
Thank u so much for fix ! 
Tell me pls how update for last stapi.patch(actual) and oscam svn...
...after compile better look likes oscam-1.20-unstable_svn VERSION-emu785-NO NAME BRAND

**Comment by satxtreme** [comment]
Thanks for support)

**Comment by satxtreme** [comment]
[oscam-1.20-unstable_svn--emu785-Openbox_Xcruiser-armeabi-v7a.zip](https://github.com/su-mak/osebuild/files/2761264/oscam-1.20-unstable_svn--emu785-Openbox_Xcruiser-armeabi-v7a.zip)
PowerVu does not work, work only from  **MAHDI-DZ**

**Comment by satxtreme** [comment]
`osebuild > blackout

2019/01/15 22:25:25 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:273DD993355383C9AE585ACAFE044966): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:25:26 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:0643FD2C7F157622E11A6ED1AF10B9CA): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:25:27 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:0D25AD5C7893ECE16FEA53DF8075F927): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:25:28 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:6A98CCE3C547D481D62841F505D8A334): found (1 ms) by emulator (L/1/2/2)
2019/01/15 22:25:29 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:063709A6D240B1905ACB21381B1C6B86): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:25:30 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:2925456548B35ED2A3FF6031E6D5DB6C): found (1 ms) by emulator (L/1/2/2)
2019/01/15 22:25:31 46C75640 c      (ecm) as4k (0E00@000000/0000/00C8/40:4ED2DE3048EFCD6AD3B4015677BEFB28): found (2 ms) by emulator (L/1/2/2)

MAHDI-DZ  >>> all good working
2019/01/15 22:35:01 26495456 c (dvbstapi)   4F 58 1A 54 B3 01 0D 31 00 00 00 00 00 00 00 00 
2019/01/15 22:35:01 26495456 c (dvbstapi)   8F EC 5D 20 92 4A 6B F7 00 00 00 00 00 00 00 00 
2019/01/15 22:35:01 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:83D4A928712C0E502FA8C36AF790C366): found (1 ms) by emulator (L/1/2/2)
2019/01/15 22:35:01 26495456 c (dvbstapi) [stapi_do_remove_filter] dev_id(1) SessionHandle [0x00010001] NumSlots(1)
2019/01/15 22:35:01 26495456 c   (dvbapi) Demuxer 0 found 1 ECMpids and 18 STREAMpids in PMT
2019/01/15 22:35:02 26495456 c (dvbstapi) MCW DES56 Dump : 
2019/01/15 22:35:02 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 EC 08 9E 15 98 70 34 2A 
2019/01/15 22:35:02 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 45 A8 F4 2F 26 CB C2 BC 
2019/01/15 22:35:02 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:6C78CF06E2E5B524B407736E0DCC692E): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:35:03 26495456 c (dvbstapi) MCW DES56 Dump : 
2019/01/15 22:35:03 26495456 c (dvbstapi)   EF 5E 1A E0 67 57 4F 6E 00 00 00 00 00 00 00 00 
2019/01/15 22:35:03 26495456 c (dvbstapi)   62 04 EA 8F 73 20 1A A8 00 00 00 00 00 00 00 00 
2019/01/15 22:35:03 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:ED5C583AEFB48B4E97766D3B4DBD08BE): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:35:04 26495456 c (dvbstapi) MCW DES56 Dump : 
2019/01/15 22:35:04 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 13 D0 52 2A CE 8F 1C 3E 
2019/01/15 22:35:04 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 8A A7 25 64 D9 CB 6D 89 
2019/01/15 22:35:04 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:20017E1ACED33CA4323D05BB5028A449): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:35:05 26495456 c (dvbstapi) MCW DES56 Dump : 
2019/01/15 22:35:05 26495456 c (dvbstapi)   A7 5E 6D EF 15 43 BC C1 00 00 00 00 00 00 00 00 
2019/01/15 22:35:05 26495456 c (dvbstapi)   A7 86 DC 7A F8 83 7A FD 00 00 00 00 00 00 00 00 
2019/01/15 22:35:05 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:89E85FFFC40B4806A0161D69F883C561): found (2 ms) by emulator (L/1/2/2)
2019/01/15 22:35:06 26495456 c (dvbstapi) MCW DES56 Dump : 
2019/01/15 22:35:06 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 A8 E9 E3 25 C8 CB 94 CD 
2019/01/15 22:35:06 26495456 c (dvbstapi)   00 00 00 00 00 00 00 00 4C 7C 8C 64 BF 6D 02 02 
2019/01/15 22:35:06 26495456 c      (ecm) as4k (0E00@000000/0000/0384/40:1F07CEAF23DBD7DDE0CF6670C09B1D3A): found (2 ms) b`

**Comment by su-mak** [comment]
At the moment, I have no idea how to solve this issue.
Try asking MAHDI-DZ to help you solve this problem.

**Comment by satxtreme** [comment]
Thanks...I tried, but to no avail

**Comment by satxtreme** [comment]
Maybe he will tell you the solution.

**Comment by satxtreme** [comment]
Hi ! Very interesting!
**AFN work OK** 
PowerVu  4.9Е **does not work** !

**Comment by su-mak** [comment]
```
wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip
unzip android-ndk-r19-linux-x86_64.zip

export ANDROID_NDK=../android-ndk-r19
export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

wget http://www.openssl.org/source/openssl-1.1.1a.tar.gz
tar -xf openssl-1.1.1a.tar.gz
cd openssl-1.1.1a
./Configure android-arm -D__ANDROID_API__=21 no-afalgeng no-aria no-asan no-asm no-async no-autoalginit no-autoerrinit no-autoload-config no-bf no-blake2 no-camellia no-capieng no-cast no-chacha no-cmac no-cms no-comp no-crypto-mdebug no-crypto-mdebug-backtrace no-ct no-deprecated no-devcryptoeng no-dgram no-dh no-dsa no-dso no-dtls no-dynamic-engine no-ec no-ec2m no-ecdh no-ecdsa no-ec_nistp_64_gcc_128 no-egd no-engine no-err no-external-tests no-filenames no-fuzz-libfuzzer no-fuzz-afl no-gost no-heartbeats no-idea no-makedepend no-md2 no-md4 no-msan no-multiblock no-nextprotoneg no-ocb no-ocsp no-pic no-poly1305 no-posix-io no-psk no-rc2 no-rc4 no-rc5 no-rdrand no-rfc3779 no-rmd160 no-scrypt no-sctp no-seed no-shared no-siphash no-sm2 no-sm3 no-sm4 no-sock no-srp no-srtp no-sse2 no-ssl no-ssl-trace no-stdio no-tests no-threads no-tls no-ts no-ubsan no-ui-console no-unit-test no-whirlpool no-weak-ssl-ciphers no-zlib no-zlib-dynamic no-ssl3 no-ssl3-method no-tls1 no-tls1-method no-tls1_1 no-tls1_1-method no-tls1_2 no-tls1_2-method no-tls1_3 no-dtls1 no-dtls1-method no-dtls1_2 no-dtls1_2-method
make
cd ../

svn checkout https://github.com/oscam-emu/oscam-patched/trunk oscam-emu
cd oscam-emu

patch -p0 < ../patches/stapi/stapi.patch

# make config

./config.sh --disable WITH_SSL CLOCKFIX CARDREADER_DB2COM

make USE_STAPI=1 STAPI_LIB="-L../patches/stapi -lwi" CONF_DIR=/data/plugin/oscam USE_UTF8=1 USE_LIBCRYPTO=1 LIBCRYPTO_LIB="../openssl-1.1.1a/libcrypto.a" CC="armv7a-linux-androideabi21-clang -I ../openssl-1.1.1a/include -Wno-invalid-command-line-argument" STRIP=arm-linux-androideabi-strip LIB_RT= LIB_PTHREAD=
```
