### ISSUE TITLE
Oscam for U4 still not working

### ISSUE THREAD

**Issue by nozorrog** [su-mak/osebuild#5]
Oscam for U4 still not working. For U5 works good.

**Comment by nozorrog** [comment]
Ooooops ) Tried to build Oscam for U4 with SSL. 
It works! )

**Comment by su-mak** [comment]
it works for me

log

OSCAM-Rev:11431-Hisilicon_U4 
Hisilicon_U4 armeabi-v7a 

Enabled configuration
WEBIF
WEBIF_LIVELOG
WEBIF_JQUERY
TOUCH
HAVE_DVBAPI
READ_SDT_CHARSETS
IRDETO_GUESSING
CS_ANTICASC
WITH_DEBUG
MODULE_MONITOR
WITH_LB
CS_CACHEEX
CW_CYCLE_CHECK
CLOCKFIX
MODULE_CAMD35
MODULE_CAMD35_TCP
MODULE_NEWCAMD
MODULE_CCCAM
MODULE_CCCSHARE
MODULE_GBOX
MODULE_RADEGAST
MODULE_SCAM
MODULE_SERIAL
MODULE_CONSTCW
MODULE_PANDORA
MODULE_GHTTP
READER_NAGRA
READER_IRDETO
READER_CONAX
READER_CRYPTOWORKS
READER_SECA
READER_VIACCESS
READER_VIDEOGUARD
READER_DRE
READER_TONGFANG
READER_BULCRYPT
READER_GRIFFIN
READER_DGCRYPT
CARDREADER_PHOENIX
CARDREADER_INTERNAL
CARDREADER_SC8IN1
CARDREADER_MP35
CARDREADER_SMARGO
CARDREADER_DB2COM
CARDREADER_STAPI
CARDREADER_STAPI5
CARDREADER_STINGER
CARDREADER_DRECAS
make --no-print-directory \
		LIB_RT= \
		LIB_PTHREAD= \
		CROSS=arm-linux-androideabi- \
		USE_HISKY=1 LIBS=-lm\ -ldl\ -L/home/pc/beta/osebuild/patches/hisilicon/u4sdk/lib\ -lhi_msp\ -lhi_common LDFLAGS=-Wl,--build-id\ -Wl,--warn-shared-textrel\ -Wl,--fatal-warnings\ -Wl,-s\ -march=armv7-a\ -Wl,--fix-cortex-a8\ -Wl,--gc-sections\ -L/home/pc/beta/osebuild/patches/hisilicon/u4sdk/lib\ -lhi_msp\ -lhi_common\ -D__ARMEL__\ -I/home/pc/beta/osebuild/patches/hisilicon/u4sdk/include\ -DWITH_HISILICON=1\ -DSDKV600\ -fPIE\ -pie CFLAGS=-g\ -DANDROID\ -ffunction-sections\ -funwind-tables\ -fstack-protector-strong\ -no-canonical-prefixes\ -Os\ -march=armv7-a\ -mfloat-abi=softfp\ -mfpu=vfpv3-d16\ -D__ARMEL__\ -I/home/pc/beta/osebuild/patches/hisilicon/u4sdk/include\ -DWITH_HISILICON=1\ -DSDKV600\ -fPIE CONF_DIR=/data/oscam OSCAM_BIN=Distribution/oscam-1.20-unstable_svn-11431-Hisilicon_U4 CROSS=/home/pc/beta/osebuild/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-

| OSCam ver: 1.20_svn rev: 11431 target: arm-linux-androideabi-his
| Tools:
|  CROSS    = /home/pc/beta/osebuild/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-
|  CC       = /home/pc/beta/osebuild/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-gcc
| Settings:
|  CONF_DIR = /data/oscam
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Os -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -D__ARMEL__ -I/home/pc/beta/osebuild/patches/hisilicon/u4sdk/include -DWITH_HISILICON=1 -DSDKV600 -fPIE -DWITH_HISKY=1
|  LDFLAGS  = -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,-s -march=armv7-a -Wl,--fix-cortex-a8 -Wl,--gc-sections -L/home/pc/beta/osebuild/patches/hisilicon/u4sdk/lib -lhi_msp -lhi_common -D__ARMEL__ -I/home/pc/beta/osebuild/patches/hisilicon/u4sdk/include -DWITH_HISILICON=1 -DSDKV600 -fPIE -pie -DWITH_HISKY=1
|  LIBS     = -lm -ldl -L/home/pc/beta/osebuild/patches/hisilicon/u4sdk/lib -lhi_msp -lhi_common -lm -ldl
|  UseFlags = USE_HISKY=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK CLOCKFIX
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER DRECAS
|  Compiler : arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
|  Config   : build/arm-linux-androideabi-his/config.mak
|  Binary   : Distribution/oscam-1.20-unstable_svn-11431-Hisilicon_U4

HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 435344 template bytes into 176702 bytes. 258642 saved bytes (59.41%).
CC	cscrypt/aes.c
CC	cscrypt/bn_add.c
CC	cscrypt/bn_asm.c
CC	cscrypt/bn_ctx.c
CC	cscrypt/bn_div.c
CC	cscrypt/bn_exp.c
CC	cscrypt/bn_lib.c
CC	cscrypt/bn_mul.c
CC	cscrypt/bn_print.c
CC	cscrypt/bn_shift.c
CC	cscrypt/bn_sqr.c
CC	cscrypt/bn_word.c
CC	cscrypt/mem.c
CC	cscrypt/des.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/md5.c
CC	cscrypt/rc6.c
CC	cscrypt/sha1.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	csctapi/ifd_db2com.c
CC	csctapi/ifd_mp35.c
CC	csctapi/ifd_phoenix.c
CC	csctapi/ifd_drecas.c
CC	csctapi/ifd_sc8in1.c
CC	csctapi/ifd_sci.c
CC	csctapi/ifd_smargo.c
CC	csctapi/ifd_stinger.c
CC	minilzo/minilzo.c
CC	module-anticasc.c
CC	module-cacheex.c
CC	module-camd35-cacheex.c
CC	module-camd35.c
CC	module-cccam-cacheex.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-constcw.c
CC	module-csp.c
CC	module-cw-cycle-check.c
CC	module-dvbapi-his.c
module-dvbapi-his.c: In function 'hifilter_ThreadModules':
module-dvbapi-his.c:328:5: warning: implicit declaration of function 'cs_sleep' [-Wimplicit-function-declaration]
     cs_sleep(10);
     ^
module-dvbapi-his.c: In function 'hidemux_Stop':
module-dvbapi-his.c:939:22: warning: unused parameter 'adapter' [-Wunused-parameter]
 hidemux_Stop(int32_t adapter, int32_t dmuxid, int32_t type, int32_t n, int32_t pid)
                      ^
module-dvbapi-his.c: At top level:
module-dvbapi-his.c:647:1: warning: 'hifilter_SetAttribute' defined but not used [-Wunused-function]
 hifilter_SetAttribute(HI_S32 s32FilterID, HIDEMUX_ATTRIB *pFltAttr)
 ^
module-dvbapi-his.c:737:1: warning: 'hifilter_GetAttr' defined but not used [-Wunused-function]
 hifilter_GetAttr(HI_S32 s32FilterID, HIDEMUX_ATTRIB *pFltAttr)
 ^
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
module-dvbapi.c:301:14: warning: 'client_name' defined but not used [-Wunused-variable]
 static char *client_name = "hisilicon";
              ^
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-remm.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-ird-guess.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-newcamd-des.c
CC	module-pandora.c
CC	module-ghttp.c
CC	module-radegast.c
CC	module-scam.c
CC	module-serial.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
CC	webif/pages.c
CC	reader-common.c
CC	reader-bulcrypt.c
CC	reader-conax.c
CC	reader-cryptoworks.c
CC	reader-dgcrypt.c
CC	reader-dre.c
CC	reader-dre-cas.c
CC	reader-dre-common.c
CC	reader-dre-st20.c
CC	reader-griffin.c
CC	reader-irdeto.c
CC	reader-nagra.c
CC	reader-seca.c
CC	reader-tongfang.c
CC	reader-viaccess.c
CC	reader-videoguard-common.c
CC	reader-videoguard1.c
CC	reader-videoguard12.c
CC	reader-videoguard2.c
CC	oscam-aes.c
CC	oscam-array.c
CC	oscam-hashtable.c
CC	oscam-cache.c
CC	oscam-chk.c
CC	oscam-client.c
CC	oscam-conf.c
CC	oscam-conf-chk.c
CC	oscam-conf-mk.c
CC	oscam-config-account.c
CC	oscam-config-global.c
CC	oscam-config-reader.c
CC	oscam-config.c
CC	oscam-ecm.c
CC	oscam-emm.c
CC	oscam-emm-cache.c
CC	oscam-failban.c
CC	oscam-files.c
CC	oscam-garbage.c
CC	oscam-lock.c
CC	oscam-log.c
CC	oscam-log-reader.c
CC	oscam-net.c
CC	oscam-llist.c
CC	oscam-reader.c
CC	oscam-simples.c
CC	oscam-string.c
CC	oscam-time.c
CC	oscam-work.c
CC	oscam.c
CONF	build/arm-linux-androideabi-his/config.c
LINK	Distribution/oscam-1.20-unstable_svn-11431-Hisilicon_U4.debug
STRIP	Distribution/oscam-1.20-unstable_svn-11431-Hisilicon_U4
