### ISSUE TITLE
svn

### ISSUE THREAD

**Issue by mihaip1948** [su-mak/osebuild#5]
I've tried to build today Oscam EMU and
got svn 11462 ! not 11486 as I expected ...
can you tell me why ?

**Comment by nozorrog** [comment]
Last official emu patch refer to Oscam svn 11462. If you want to build latest Oscam-emu binary, do use temporary emu patch from streamboard team.

**Comment by nozorrog** [comment]
Here It is. 
[oscam-emu.patch.zip](https://github.com/su-mak/osebuild/files/2782968/oscam-emu.patch.zip)

**Comment by mihaip1948** [comment]
Type	Name	Latest commit message	Commit time
application	new	2 months ago
packages	stapi svn11486	19 hours ago
patches/stapi	stapi svn11486	19 hours ago
LICENSE	Update	3 months ago
README.md	small repairs	2 months ago
build.sh	stapi svn11486


Viwwing this I've believed I can build svn 11486 ! with or without EMU !
but is building 11462 whatever options I made !!!

**Comment by nozorrog** [comment]
I see You use build.sh for Oscam building with this problem. Did You try to use OSEbuild.sh? Is there same problem?

**Comment by mihaip1948** [comment]
YES ! I've used build.sh !!! I'll try with OSEbuild.sh !!! tnks !

**Comment by nozorrog** [comment]
To reduce binary file size You may turn on the built-in upx packer.
[oscam-120-unstable_svn-11486-emu785-Amiko_A5-ssl-upx.zip](https://github.com/su-mak/osebuild/files/2783936/oscam-120-unstable_svn-11486-emu785-Amiko_A5-ssl-upx.zip)
[oscam-120-unstable_svn-11486-emu785-Amiko_A5-upx.zip](https://github.com/su-mak/osebuild/files/2783937/oscam-120-unstable_svn-11486-emu785-Amiko_A5-upx.zip)

**Comment by nozorrog** [comment]
I attached here new "oscam-emu.patch" file that works well with build.sh script.
[oscam_11486_r785_Amiko.zip](https://github.com/su-mak/osebuild/files/2784013/oscam_11486_r785_Amiko.zip)
[oscam-emu.zip](https://github.com/su-mak/osebuild/files/2784017/oscam-emu.zip)

**Comment by mihaip1948** [comment]
Tnks a lot ! based on oscam-emu you give me , 
and openssl build by osebuild ... I've managed
to build both ... e2 and ndk versions of oscam
using my manual "toolchain" ...  Thanks again !
