### ISSUE TITLE
new error building Oscam with emu 772

### ISSUE THREAD

**Issue by nozorrog** [su-mak/osebuild#6]
After the new Oscam-emu patch v.772 is out, I get error building Oscam binary.
Here is the log. Thanx!

-------------------------------------------
             ./OSEbuild.sh
------------------------------------------
OSCAM-emu772-Rev:11434-Android_4.4_KitKat-arm 
Android_4.4_KitKat-arm armeabi-v7a 
------------------------------------------
Enabled configuration --------------------
WEBIF
WEBIF_LIVELOG
WEBIF_JQUERY
TOUCH
WITH_SSL
HAVE_DVBAPI
WITH_NEUTRINO
READ_SDT_CHARSETS
IRDETO_GUESSING
CS_ANTICASC
WITH_DEBUG
MODULE_MONITOR
WITH_LB
CS_CACHEEX
CW_CYCLE_CHECK
LCDSUPPORT
LEDSUPPORT
CLOCKFIX
WITH_EMU
MODULE_CAMD35
MODULE_CAMD35_TCP
MODULE_NEWCAMD
MODULE_CCCAM
MODULE_CCCSHARE
MODULE_GBOX
MODULE_RADEGAST
MODULE_SCAM
MODULE_SERIAL
MODULE_CONSTCW
MODULE_PANDORA
MODULE_GHTTP
READER_NAGRA
READER_NAGRA_MERLIN
READER_IRDETO
READER_CONAX
READER_CRYPTOWORKS
READER_SECA
READER_VIACCESS
READER_VIDEOGUARD
READER_DRE
READER_TONGFANG
READER_BULCRYPT
READER_GRIFFIN
READER_DGCRYPT
CARDREADER_PHOENIX
CARDREADER_INTERNAL
CARDREADER_SC8IN1
CARDREADER_MP35
CARDREADER_SMARGO
CARDREADER_DB2COM
CARDREADER_STAPI
CARDREADER_STAPI5
CARDREADER_STINGER
CARDREADER_DRECAS
make --no-print-directory \
		LIB_RT= \
		LIB_PTHREAD= \
		CROSS=arm-linux-androideabi- \
		USE_SSL=1 LDFLAGS=-Wl,--build-id\ -Wl,--warn-shared-textrel\ -Wl,--fatal-warnings\ -Wl,-s\ -march=armv7-a\ -Wl,--fix-cortex-a8\ -fPIE\ -pie CFLAGS=-g\ -DANDROID\ -ffunction-sections\ -funwind-tables\ -fstack-protector-strong\ -no-canonical-prefixes\ -Os\ -march=armv7-a\ -mfloat-abi=softfp\ -mfpu=vfpv3-d16\ -fPIE CONF_DIR=/var/tuxbox/config OSCAM_BIN=Distribution/oscam-1.20-unstable_svn-11434-emu772-Android_4.4_KitKat-arm-ssl USE_UTF8=1 USE_LIBCRYPTO=1 CROSS=/mnt/c/oscam/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-
+-------------------------------------------------------------------------------
| OSCam ver: 1.20_svn rev: 11434 target: arm-linux-androideabi-ssl
| Tools:
|  CROSS    = /mnt/c/oscam/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-
|  CC       = /mnt/c/oscam/tmp/toolchains/Android_4.4_KitKat-arm/bin/arm-linux-androideabi-gcc
| Settings:
|  CONF_DIR = /var/tuxbox/config
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Os -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fPIE -fexpensive-optimizations -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_UTF8=1 -DWITH_UTF8
|  LDFLAGS  = -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,-s -march=armv7-a -Wl,--fix-cortex-a8 -fPIE -pie -DWITH_SSL=1 -DWITH_LIBCRYPTO=1 -DWITH_UTF8=1 -DWITH_UTF8
|  LIBS     = -lssl -lcrypto -lm -ldl
|  UseFlags = USE_SSL=1 USE_LIBCRYPTO=1 USE_UTF8=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH WITH_SSL HAVE_DVBAPI WITH_NEUTRINO READ_SDT_CHARSETS IRDETO_GUESSING CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CW_CYCLE_CHECK LCDSUPPORT LEDSUPPORT CLOCKFIX WITH_EMU
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST SCAM SERIAL CONSTCW PANDORA GHTTP
|  Readers  : NAGRA NAGRA_MERLIN IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL SC8IN1 MP35 SMARGO DB2COM STAPI STAPI5 STINGER DRECAS
|  Compiler : arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
|  Config   : build/arm-linux-androideabi-ssl/config.mak
|  Binary   : Distribution/oscam-1.20-unstable_svn-11434-emu772-Android_4.4_KitKat-arm-ssl
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 440776 template bytes into 178619 bytes. 262157 saved bytes (59.48%).
CC	cscrypt/des.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/md5.c
CC	cscrypt/rc6.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	csctapi/ifd_db2com.c
CC	csctapi/ifd_mp35.c
CC	csctapi/ifd_phoenix.c
CC	csctapi/ifd_drecas.c
CC	csctapi/ifd_sc8in1.c
CC	csctapi/ifd_sci.c
CC	csctapi/ifd_smargo.c
CC	csctapi/ifd_stinger.c
CC	minilzo/minilzo.c
CC	module-anticasc.c
CC	module-cacheex.c
CC	module-camd35-cacheex.c
CC	module-camd35.c
CC	module-cccam-cacheex.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-constcw.c
CC	module-emulator.c
CC	module-emulator-osemu.c
module-emulator-osemu.c: In function 'PowervuHashModes15to19Tables':
module-emulator-osemu.c:3587:3: warning: implicit declaration of function '__bswap_32' [-Wimplicit-function-declaration]
   d = __bswap_32(*(uint32_t *)(data + i));
   ^
CC	module-emulator-stream.c
CC	ffdecsa/ffdecsa.c
CC	module-csp.c
CC	module-cw-cycle-check.c
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-remm.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-ird-guess.c
CC	module-lcd.c
CC	module-led.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-newcamd-des.c
CC	module-pandora.c
CC	module-ghttp.c
CC	module-radegast.c
CC	module-scam.c
CC	module-serial.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
CC	webif/pages.c
CC	reader-common.c
CC	reader-bulcrypt.c
CC	reader-conax.c
CC	reader-cryptoworks.c
CC	reader-dgcrypt.c
CC	reader-dre.c
CC	reader-dre-cas.c
CC	reader-dre-common.c
CC	reader-dre-st20.c
CC	reader-griffin.c
CC	reader-irdeto.c
CC	reader-nagra.c
CC	cscrypt/mdc2.c
CC	cscrypt/aescbc.c
CC	cscrypt/fast_aes.c
CC	cscrypt/sha256.c
CC	reader-nagracak7.c
CC	reader-seca.c
CC	reader-tongfang.c
CC	reader-viaccess.c
CC	reader-videoguard-common.c
CC	reader-videoguard1.c
CC	reader-videoguard12.c
CC	reader-videoguard2.c
CC	oscam-aes.c
CC	oscam-array.c
CC	oscam-hashtable.c
CC	oscam-cache.c
CC	oscam-chk.c
CC	oscam-client.c
CC	oscam-conf.c
CC	oscam-conf-chk.c
CC	oscam-conf-mk.c
CC	oscam-config-account.c
CC	oscam-config-global.c
CC	oscam-config-reader.c
CC	oscam-config.c
CC	oscam-ecm.c
CC	oscam-emm.c
CC	oscam-emm-cache.c
CC	oscam-failban.c
CC	oscam-files.c
CC	oscam-garbage.c
CC	oscam-lock.c
CC	oscam-log.c
CC	oscam-log-reader.c
CC	oscam-net.c
CC	oscam-llist.c
CC	oscam-reader.c
CC	oscam-simples.c
CC	oscam-string.c
CC	oscam-time.c
CC	oscam-work.c
CC	oscam.c
CONF	build/arm-linux-androideabi-ssl/config.c
LINK	Distribution/oscam-1.20-unstable_svn-11434-emu772-Android_4.4_KitKat-arm-ssl.debug
module-emulator-osemu.c:3587: error: undefined reference to '__bswap_32'
module-emulator-osemu.c:3595: error: undefined reference to '__bswap_32'
module-emulator-osemu.c:3596: error: undefined reference to '__bswap_32'
module-emulator-osemu.c:3597: error: undefined reference to '__bswap_32'
collect2: error: ld returned 1 exit status
make[2]: *** [Distribution/oscam-1.20-unstable_svn-11434-emu772-Android_4.4_KitKat-arm-ssl.debug] Error 1
make[1]: *** [all] Error 2
make: *** [android-arm] Error 2
------------------------------------------
Tue Oct 16 18:12:53 DST 2018
------------------------------------------

**Comment by su-mak** [comment]
### **oscam-emu plus patch**

```
Index: module-emulator-osemu.c
===================================================================
--- module-emulator-osemu.c	(v.772)
+++ module-emulator-osemu.c	(working copy)
@@ -3584,7 +3584,11 @@
 		c = c0 + c1;
 
 		#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
+			#if defined(__ANDROID__)
+			d = bswap_32(*(uint32_t *)(data + i));
+			#else
 		d = __bswap_32(*(uint32_t *)(data + i));
+			#endif
 		#else
 		d =            *(uint32_t *)(data + i);
 		#endif
@@ -3592,10 +3596,17 @@
 	}
 
 	#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
+		#if defined(__ANDROID__)
+		*(uint32_t *)(hash + 0) = bswap_32(h[0]);
+		*(uint32_t *)(hash + 4) = bswap_32(h[1]);
+		*(uint32_t *)(hash + 8) = bswap_32(h[2]);
+		*(uint32_t *)(hash + 12)= bswap_32(h[3]);
+		#else
 	*(uint32_t *)(hash + 0) = __bswap_32(h[0]);
 	*(uint32_t *)(hash + 4) = __bswap_32(h[1]);
 	*(uint32_t *)(hash + 8) = __bswap_32(h[2]);
 	*(uint32_t *)(hash + 12)= __bswap_32(h[3]);
+		#endif
 	#else
 	*(uint32_t *)(hash + 0) =           (h[0]);
 	*(uint32_t *)(hash + 4) =           (h[1]);
```

**Comment by nozorrog** [comment]
Is it possible to merge this patch with original oscam-emu patch to use It for building Oscam binary by OSEbuild.sh? Or how can I use this plus patch with OSEbuild.sh?

**Comment by su-mak** [comment]
Ask @oscam-emu to paste, fix it.
https://github.com/oscam-emu/oscam-emu/commit/9e07fbc848895c9c62af24137c9c0771294aec52

```
Index: module-emulator-osemu.c
===================================================================
--- module-emulator-osemu.c	(revision 1527)
+++ module-emulator-osemu.c	(working copy)
@@ -10,6 +10,10 @@
 #include <endian.h>
 #include <byteswap.h>
 
+#if defined(__ANDROID__)
+#define __bswap_32 bswap_32
+#endif
+
 #ifdef WITH_EMU
 #include "oscam-aes.h"
 #include "oscam-string.h"
```

with this or something...

**Comment by oscam-emu** [comment]
Fixed with https://github.com/oscam-emu/oscam-emu/commit/d03f197305cfc735ee78415e38e425ff53ebb311

**Comment by nozorrog** [comment]
Well done! It works.
