### ISSUE TITLE
Entitlements for emulator

### ISSUE THREAD

**Issue by AZBoxEmperador** [su-mak/osebuild#8]
Click under CARDOK (1756 entitlements) will pop a screen like the one bellow, this is not working with the last OSCAM version...

![image](https://user-images.githubusercontent.com/4449023/47539129-5d7c8080-d894-11e8-9d6c-89fbd2a1a39a.png)

**Comment by AZBoxEmperador** [comment]
this is fixed by adding this reader to oscam.server

[reader]
label                         = myslot
protocol                      = internal
device                        = /dev/hi_sci
boxid                         = 01234567
detect                        = cd
mhz                           = 9600
cardmhz                       = 320
aeskeys                       = 0500@030B00:0,A79AC0DBEC9C9251D1915F058862AF26,0,0,0,0,0,0,0,0,0,0,9A3EAB0203EBFFCA85B4F18280749F56;0500@032820:B10E2276555C127361818CE2B9F1E7D4,B10E2276555C127361818CE2B9F1E7D4,B10E2276555C127361818CE2B9F1E7D4
group                         = 1

**Comment by su-mak** [comment]
The internal HISKY "/dev/hi_sci" card reader is not ready yet.
