### ISSUE TITLE
DVB Api Config tab - PMT Mode does not change

### ISSUE THREAD

**Issue by AZBoxEmperador** [su-mak/osebuild#9]
under Edit DVB Api Config tab PMT mode does not change from "1 - disable reading PMT file" to any other option. 

![image](https://user-images.githubusercontent.com/4449023/47539372-b26cc680-d895-11e8-86e6-ab31d25d39cf.png)

**Comment by su-mak** [comment]
Fixed with: https://github.com/su-mak/osebuild/commit/2398d94de59b0838281653f0f2b0d246837d8112

**Comment by AZBoxEmperador** [comment]
this issue is fixed
